version: '3'

services:

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
    - .:/usr/recipes-django
    command: >
      sh -c "python ./src/manage.py wait_for_db &&
             python ./src/manage.py migrate &&
             python ./src/manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=pwd123
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pwd123
